# Generated by Django 4.0.2 on 2022-02-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Definitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='jobposting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to='Definitions.jobposting'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobPosting', to='Definitions.company'),
        ),
    ]
