name: GitlabSync

on:
  - push
  - delete

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
    - uses: icub-tech-iit/gh-action-repo-selective-sync@v1.0.0
      with:
        recipe-file: '.publish/recipe.yml'
        token-source: main
        token-target: ${{ secrets.TARGET_TOKEN }}
